#!/usr/bin/sh

echo "Running pre-commit..."

echo "Autoformatting Python files..."
black .

echo "Autoformatting C++ files..."
clang-format -i $(find . -name "*.cpp" -o -name "*.h")

echo "Pre-commit done!"
