---
repos:
    - repo: https://github.com/pycqa/flake8
      rev: 3.9.0
      hooks:
          - id: flake8

    - repo: https://github.com/psf/black
      rev: 20.8b1
      hooks:
          - id: black
            language_version: python3

    - repo: https://github.com/adrienverge/yamllint.git
      rev: v1.26.1
      hooks:
          - id: yamllint
            args: [-c=./.yamllint.yaml, --strict]

    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.1.0
      hooks:
          - id: yamlfmt
